;;;
;;; Copyright (c) 2015 Andrej Vodopivec <andrej.vodopivec@gmail.com>
;;;
;;; Permission is hereby granted, free of charge, to any person obtaining a copy
;;; of this software and associated documentation files (the "Software"), to deal
;;; in the Software without restriction, including without limitation the rights
;;; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
;;; copies of the Software, and to permit persons to whom the Software is
;;; furnished to do so, subject to the following conditions:
;;;
;;; The above copyright notice and this permission notice shall be included in
;;; all copies or substantial portions of the Software.
;;; 
;;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
;;; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
;;; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
;;; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
;;; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
;;; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
;;; THE SOFTWARE.
;;;

(defpackage :simple-tk
  (:use :cl
        :split-sequence
        :cffi)
  (:nicknames :tk)
  (:documentation
"This package is a simple wrapper for the TCL interpreter and TK gui. 

For a more detailed information about functions look at the tcl/tk 
documentation. For instance, the method @code{canvas-addtag-withtag} 
corresonds to the command @code{addtag}, subcommand @code{withtag} on 
the canvas object. The call 
@code{(canvas-addtag-withtag cnv ntag otag)} is transformed into the tcl 
call @code{cnv addtag ntag withtag otag}.")
  (:export :after
           :after-cancel
           :after-idle
           :bind-command
           :bind-event
           :boolean-var
           :button
           :button-invoke
           :canvas
           :canvas-addtag
           :canvas-addtag-above
           :canvas-addtag-all
           :canvas-addtag-blow
           :canvas-addtag-closest
           :canvas-addtag-enclosed
           :canvas-addtag-overlapping
           :canvas-addtag-withtag
           :canvas-bbox
           :canvas-bind
           :canvas-canvasx
           :canvas-canvasy
           :canvas-coords
           :canvas-create
           :canvas-create-arc
           :canvas-create-bitmap
           :canvas-create-image
           :canvas-create-line
           :canvas-create-oval
           :canvas-create-photo
           :canvas-create-poylgon
           :canvas-create-rectangle
           :canvas-create-text
           :canvas-create-window
           :canvas-dchars
           :canvas-delete
           :canvas-dtag
           :canvas-find
           :canvas-find-above
           :canvas-find-all
           :canvas-find-below
           :canvas-find-closest
           :canvas-find-enclosed
           :canvas-find-overlapping
           :canvas-find-withtag
           :canvas-focus
           :canvas-gettags
           :canvas-icursor
           :canvas-imove
           :canvas-index
           :canvas-insert
           :canvas-image-cget
           :canvas-image-configure
           :canvas-image-names
           :canvas-itemcget
           :canvas-itemconfig
           :canvas-lower
           :canvas-move
           :canvas-moveto
           :canvas-postscript
           :canvas-raise
           :canvas-rchars
           :canvas-scale
           :canvas-scan-dragto
           :canvas-scan-mark
           :canvas-scrolled-coords
           :canvas-select-adjust
           :canvas-select-clear
           :canvas-select-from
           :canvas-select-item
           :canvas-select-to
           :canvas-type
           :canvas-xview
           :canvas-xview-moveto
           :canvas-xview-scroll
           :canvas-yview
           :canvas-yview-moveto
           :canvas-yview-scroll
           :checkbutton
           :choose-color
           :choose-directory
           :clipboard-append
           :clipboard-clear
           :clipboard-get
           :combobox
           :combobox-current
           :configure-window
           :create-command
           :entry
           :entry-bbox
           :entry-delete
           :entry-get
           :entry-icursor
           :entry-index
           :entry-insert
           :entry-selection-adjust
           :entry-selection-clear
           :entry-selection-from
           :entry-selection-present
           :entry-selection-range
           :entry-selection-to
           :entry-validate
           :entry-xview
           :entry-xview-moveto
           :entry-xview-scroll
           :event-key-code
           :event-mouse-position
           :event-window-path
           :float-var
           :frame
           :font-configure
           :font-create
           :font-delete
           :font-families
           :font-format
           :font-names
           :get-open-file
           :get-save-file
           :get-tk-themes
           :grab-release
           :grab-set
           :grab-status
           :grid
           :grid-configure
           :grid-columnconfigure
           :grid-forget
           :grid-info
           :grid-rowconfigure
           :grid-slaves
           :image-blank
           :image-cget
           :image-configure
           :image-copy
           :image-create-bitmap
           :image-create-photo
           :image-data
           :image-get
           :image-read
           :image-redither
           :image-transparency
           :image-write
           :integer-var
           :label
           :label-frame
           :listbox
           :listbox-activate
           :listbox-bbox
           :listbox-curselection
           :listbox-delete
           :listbox-insert
           :listbox-scan-dragto
           :listbox-scan-mark
           :listbox-see
           :listbox-xview
           :listbox-xview-moveto
           :listbox-xview-scroll
           :listbox-yview
           :listbox-yview-moveto
           :listbox-yview-scroll
           :menu
           :menu-add-cascade
           :menu-add-checkbutton
           :menu-add-command
           :menu-add-radio
           :menu-add-separator
           :menu-popup
           :menubutton
           :message
           :message-box
           :notebook
           :notebook-add
           :notebook-forget
           :notebook-hide
           :notebook-identify-element
           :notebook-identify-tab
           :notebook-index
           :notebook-insert
           :notebook-select
           :notebook-tab
           :notebook-tabs
           :pack
           :pack-configure
           :pack-forget
           :pack-infopla
           :pack-slaves
           :panedwindow
           :panedwindow-add
           :panedwindow-forget
           :panedwindow-identify-element
           :panedwindow-identify-sash
           :panedwindow-insert
           :panedwindow-sashpos
           :place
           :place-configure
           :place-forget
           :place-info
           :place-slaves
           :progressbar
           :progressbar-start
           :progressbar-step
           :progressbar-stop
           :radiobutton
           :scale
           :scrollbar
           :scrollbar-connect
           :separator
           :set-tk-theme
           :spinbox
           :string-var
           :text
           :text-bbox
           :text-count-chars
           :text-count-displaychars
           :text-count-displayindices
           :text-count-displaylines
           :text-count-indices
           :text-count-lines
           :text-count-xpixels
           :text-count-ypixels
           :text-delete
           :text-dlineinfo
           :text-edit-modified
           :text-edit-redo
           :text-edit-reset
           :text-edit-separator
           :text-edit-undo
           :text-get
           :text-get-displaychars
           :text-index
           :text-insert
           :text-image-cget
           :text-image-configure
           :text-image-create
           :text-image-names
           :text-mark-gravity
           :text-mark-names
           :text-mark-next
           :text-mark-previous
           :text-mark-set
           :text-mark-unset
           :text-replace
           :text-search
           :text-see
           :text-tag-add
           :text-tag-bind
           :text-tag-cget
           :text-tag-config
           :text-tag-delete
           :text-tag-lower
           :text-tag-names
           :text-tag-raise
           :text-window-create
           :text-window-cget
           :text-window-configure
           :text-window-names
           :text-xview
           :text-xview-moveto
           :text-xview-scroll
           :text-yview
           :text-yview-moveto
           :text-yview-scroll
           #+darwin :tk-mac-about-panel
           #+darwin :tk-mac-show-help
           #+darwin :tk-mac-show-preferences
           #+darwin :tk-mac-quit
           :tk-version
           :toplevel
           :trace-var
           :treeview
           :treeview-bbox
           :treeview-children
           :treeview-column-anchor
           :treeview-column-id
           :treeview-column-minwidth
           :treeview-column-stretch
           :treeview-column-width
           :treeview-delete
           :treeview-detach
           :treeview-exists
           :treeview-focus
           :treeview-get
           :treeview-heading-anchor
           :treeview-heading-image
           :treeview-heading-text
           :treeview-insert
           :treeview-item-id
           :treeview-item-text
           :treeview-item-values
           :treeview-move
           :treeview-next
           :treeview-parent
           :treeview-prev
           :treeview-selection
           :treeview-selection-add
           :treeview-selection-remove
           :treeview-selection-set
           :treeview-selection-toggle
           :treeview-set
           :var-value
           :window-children
           :window-cget
           :window-configure
           :window-deiconify
           :window-destroy
           :window-focus
           :window-from-path
           :window-geometry
           :window-height
           :window-iconify
           :window-iconphoto
           :window-identify
           :window-identify-element
           :window-lower
           :window-maxsize
           :window-minsize
           :window-pointerx
           :window-pointerxy
           :window-pointery
           :window-protocol
           :window-raise
           :window-resizable
           :window-reqheight
           :window-reqwidth
           :window-screenheight
           :window-screenwidth
           :window-state
           :window-title
           :window-width
           :window-withdraw
           :window-transient
           :window-wait
           :with-tk-root))

